//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtpProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjige
    {
        public int Id { get; set; }
        public string NazivKnjige { get; set; }
        public string Kategorija { get; set; }
        public int Količina { get; set; }
        public string ISBN { get; set; }
        public string Autor { get; set; }
    }
}
